# Generated by Django 6.0.3 on 2026-03-28 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Main reason for the visit')),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80 mmHg', max_length=20, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, help_text='%', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('diagnosis', models.TextField()),
                ('icd10_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='ICD-10 Code')),
                ('prescription', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('referrals', models.TextField(blank=True, help_text='Referrals to specialists or exams', null=True)),
                ('follow_up_in_days', models.PositiveSmallIntegerField(blank=True, help_text='Follow-up in X days', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='records/attachments/%Y/%m/')),
                ('attachment_type', models.CharField(choices=[('exam_result', 'Exam Result'), ('image', 'Image'), ('prescription', 'Prescription'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.medicalrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record Attachment',
                'verbose_name_plural': 'Record Attachments',
            },
        ),
    ]
